### ISSUE TITLE
Cannot drag "Generic ble X" node to flow

### ISSUE THREAD

**Issue by Eystorhaf** [CANDY-LINE/node-red-contrib-generic-ble#18] opened 2019-06-24 08:48 UTC
Dear all,

I installed the package and all respective nodes are appearing in the palette overview.
But I cannot drag one of the nodes to my flow. Any idea why this might be happening?

Best regards,

Matthias

**Comment by akobelan** [comment] 2019-07-05 00:51
I had the same issue. Modify your settings.js file such that:

`// To enabled pretty-printing of the flow within the flow file, set the following
    //  property to true:
    flowFilePretty: true,`

Then your flows*.json file will format nicely when you "Deploy". Stop node-red and open your favourite editor on flows*.json. Search for BLE. Here are two in my flows*.json file.

`    {
        "id": "9a63b336.14763",
        "type": "Generic BLE out",
        "z": "d4f9f4e0.1aead8",
        "name": "",
        "genericBle": "3d401eeb.7be6ca",
        "x": -110,
        "y": 80,
        "wires": []
    },
    {
        "id": "485080f9.140b7",
        "type": "Generic BLE in",
        "z": "d4f9f4e0.1aead8",
        "name": "",
        "useString": false,
        "notification": true,
        "x": -100,
        "y": 140,
        "wires": [
            []
        ]
    }
`

Interestingly, the "x" component will be negative. Remove the negative sign and then save your file. That will effectively pull the node back onto the canvas. I was there all along, just off, to the right of canvas.

Your flows*.json file should now look like:

`    {
        "id": "9a63b336.14763",
        "type": "Generic BLE out",
        "z": "d4f9f4e0.1aead8",
        "name": "",
        "genericBle": "3d401eeb.7be6ca",
        "x": 110,
        "y": 80,
        "wires": []
    },
    {
        "id": "485080f9.140b7",
        "type": "Generic BLE in",
        "z": "d4f9f4e0.1aead8",
        "name": "",
        "useString": false,
        "notification": true,
        "x": 100,
        "y": 140,
        "wires": [
            []
        ]
    }
`

Restart node-red and open the tab you think the BLE node(s) should be. They should appear. until the problem is fixed upstream, just "copy"/"paste" the BLE node as required.

Yes, its a work-around. But this "solved" my problem for the time being.

**Comment by dbaba** [comment] 2019-07-05 06:44
@Eystorhaf Are you using Node-RED v0.20.6? If so, this is a NR issue. Use v0.20.5 or before. The incoming NR release includes the issue fix according to the NR developer team.

**Comment by dbaba** [comment] 2019-10-04 12:22
Close this. You can re-open this if you still find the same issue.

**Closed by dbaba** 2019-10-04 12:22 UTC
